openapi: 3.0.3
info:
 title: Product search API

paths:
 /products:
  get:
   summary: search for products
   parameters:
   - $ref: '#/components/parameters/LimitParam'
   - $ref: '#/components/parameters/SearchQueryParam'
   responses:
    '200':
      description: List of products
      content:
       application/json:
        schema:
         type: array
         items:
         $ref: '#/components/schemas/Product'
        example:
         summary: Many products
         value:
          - name: "Lait Canfia 1L"
            expiration_datetime: "2025-12-01T00:00:00"
            price: 5000.00
          - name: "Poire 1kg"
            expiration_datetime: "2025-10-10T00:00:00"
            price: 4999.99
         epmtyList:
          summary: No product found 
          value: []

    '404':
      description: product not found

components:
 schemas:
  product:
   type: objet
   properties:
    name:
     type: string
    expiration_datetime:
     type: string
     format: date-time
    price: 
     type: number
     format: float
parameters:
 LimitParam:
  name: limit
  in: query 
  description: Maximum number of product to return 
  required: false
  schema: 
   type: integer
   example:
    defaultTime:
     value: 10
    smallTime:
     value: 3
 SearchQueryParam:
  name: q
  in: query
  description: Search term
  required: false
  schema:
   type: string
   example:
    dairy:
     value: "pomme"
    empty:
     value: ""
